02 functions
Loori-R/wgforge_platform_frontend_course pull request #2
Opened 2019-04-10 15:05 UTC by Loori-R

были ГОСы, не успел...27/33 тестов

2019-04-21 11:17 UTC, artur-code requested changes
в целом подход интересный, молодец, нужен рефакторинг

2019-04-21 11:17 UTC, artur-code commented on 02_functions/practice/exercises/query.js
>   * 3. Реализовать функциональность создания INSERT и DELETE запросов. Написать для них тесты.
В коде ни одного отступа, страдает форматирование. Вот так выглядит удобочитаемый отформатированный код: 
```
gte: (value) => {
      if (typeof value === 'number') {
          result.query += ` = ${value}` 
      } else { 
          result.query += ` >= '${value}'`     
      }

      return WHERE_METHODS
    },
```

Вердит, код на рефакторинг. Читать Макконелла

2019-04-21 11:17 UTC, artur-code commented on 02_functions/practice/exercises/WhereMethods.js
> +            return "After calling not(), you can only call the same methods that uses where to compare."
возвращать ошибку в тексотовом виде в качестве результата выполнения функции не правильно, такую ошибку сложно перехватывать в коде который будет потреблять твою функцию, нужно выбрасывать исключение

2019-04-21 11:17 UTC, artur-code commented on 02_functions/practice/exercises/WhereMethods.js
> +            else { return item }
else лишний можно после if проверки всегда делать return

2019-04-21 11:17 UTC, artur-code commented on 02_functions/practice/exercises/QueryMethods.js
> +        this.select = (...args) => {
у тебя не функция как класс а класс обращения через this избыточны

2019-04-21 11:17 UTC, artur-code commented on 02_functions/practice/exercises/CommonMethods.js
> +        const whereOrAnd = array[0]
тут напрашивается ассоциативный массив а не массив

2019-04-23 21:31 UTC, Loori-R commented on 02_functions/practice/exercises/WhereMethods.js
> +            return "After calling not(), you can only call the same methods that uses where to compare."
fixed a28508bb4608fb89ab09057917baa7ac23fd9a76

2019-04-23 21:59 UTC, Loori-R commented on 02_functions/practice/exercises/WhereMethods.js
> +            else { return item }
## Fixed: 5bd23eff309426dcdbbce9f238907f17e879cc68
<hr>

## Вопрос: 
если у нас условие для одной переменной и если все ок, мы проверяем другую переменную, то их лучше поместить в отдельные блоки или в один:

`один блок`
````
        if (typeof fieldName !== 'string') {
            return new TypeError('arguments not be string')
        } else if (this.getQueryResult.where) {
            this.getQueryResult.where.push(['AND', fieldName])
        } else {
            this.setQueryResult('where', ['WHERE', fieldName])
        }    
```` 
<hr>

`разные блоки`
````
        if (typeof fieldName !== 'string') {
            return new TypeError('arguments not be string')
        }

        if (this.getQueryResult.where) {
            this.getQueryResult.where.push(['AND', fieldName])
        } else {
            this.setQueryResult('where', ['WHERE', fieldName])
        }
````

2019-04-23 22:16 UTC, Loori-R commented on 02_functions/practice/exercises/QueryMethods.js
> +        this.select = (...args) => {
Добавлял, чтобы прошли тесты на имеющиеся методы(проверяется через Object.keys(obj)). Нужен итератор...

2019-04-23 22:17 UTC, Loori-R commented on 02_functions/practice/exercises/query.js
>   * 3. Реализовать функциональность создания INSERT и DELETE запросов. Написать для них тесты.
Fixed 2da1a6b999a54ba676a4ca22b7c1afe9adb59a44

2019-04-27 15:56 UTC, Loori-R commented on 02_functions/practice/exercises/CommonMethods.js
> +        const whereOrAnd = array[0]
fixed b18f439b587d472dd420945ef89de0295044c14b

2020-04-16 14:01 UTC, merged