03 iterators
Loori-R/wgforge_platform_frontend_course pull request #3
Opened 2019-04-17 11:00 UTC by Loori-R

deepMerge() needs refactoring

2019-04-21 11:21 UTC, artur-code requested changes

2019-04-21 11:21 UTC, artur-code commented on 03_iterators/practice/exercises/cloneDeep.js
> +    const item = sourceObject[i]
перебираешь свойства прототипа объекта, вспоминаем лекцию про итераторы

2019-04-21 11:21 UTC, artur-code commented on 03_iterators/practice/exercises/deepMerge.js
> +  helper(destinationObject, res)
helper функция избыточная и запутывает код, тут можно обойтись простым рекурсивным алгоритмом

2019-04-21 11:21 UTC, artur-code commented on 03_iterators/practice/exercises/zipObject.js
> +  while (index < keys.length) {
Через forEach метод массива можно реализовать без доп переменной и компактней. while цикл хорошо использовать когда есть какие то сложные условия или не зависящие от итерируемой структуры данных

2019-04-24 13:52 UTC, Loori-R commented on 03_iterators/practice/exercises/zipObject.js
> +  while (index < keys.length) {
Fixed 94bee099274bac03c7e8be7cf669b082adb0854e

2019-04-28 18:58 UTC, Loori-R commented on 03_iterators/practice/exercises/cloneDeep.js
> +    const item = sourceObject[i]
Fixed 0acd28349752fc87732d974e0f523b8cd2549a73

2019-04-28 19:15 UTC, Loori-R commented on 03_iterators/practice/exercises/deepMerge.js
> +  helper(destinationObject, res)
Fixed d0f581a9aa6eed6024008626c0673a3223c623c4

2020-04-16 14:00 UTC, merged